### ISSUE TITLE
Crash when saving durability info config

### ISSUE THREAD

**Issue by Pystro** [Zyin055/zyinhud#35]
I am getting a crash whenever i try to switch off the auto-equipping of low durability items. The crash happes exactly when i click the "save" button.
This happens all the time, even when i load only this one mod into minecraft.
Here is the crash report:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 25.01.15 18:45
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -96
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at com.zyin.zyinhud.ZyinHUDConfig.ReadConfigSettings(ZyinHUDConfig.java:785)
	at com.zyin.zyinhud.ZyinHUDConfig.SaveConfigSettings(ZyinHUDConfig.java:74)
	at com.zyin.zyinhud.gui.GuiZyinHUDOptions.func_146281_b(GuiZyinHUDOptions.java:1373)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:780)
	at com.zyin.zyinhud.gui.GuiZyinHUDOptions.func_146284_a(GuiZyinHUDOptions.java:620)
	at com.zyin.zyinhud.gui.GuiZyinHUDOptions.func_73864_a(GuiZyinHUDOptions.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at com.zyin.zyinhud.ZyinHUDConfig.ReadConfigSettings(ZyinHUDConfig.java:785)
	at com.zyin.zyinhud.ZyinHUDConfig.SaveConfigSettings(ZyinHUDConfig.java:74)
	at com.zyin.zyinhud.gui.GuiZyinHUDOptions.func_146281_b(GuiZyinHUDOptions.java:1373)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:780)
	at com.zyin.zyinhud.gui.GuiZyinHUDOptions.func_146284_a(GuiZyinHUDOptions.java:620)
	at com.zyin.zyinhud.gui.GuiZyinHUDOptions.func_73864_a(GuiZyinHUDOptions.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: com.zyin.zyinhud.gui.GuiZyinHUDOptions

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Pystro'/10876816, l='MpServer', x=2856,53, y=8,62, z=-2479,58]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (737,200,-1268), Chunk: (at 1,12,12 in 46,-80; contains blocks 736,0,-1280 to 751,255,-1265), Region: (1,-3; contains chunks 32,-96 to 63,-65, blocks 512,0,-1536 to 1023,255,-1025)
	Level time: 498259265 game time, 506243104 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 28 total; [EntityClientPlayerMP['Pystro'/10876816, l='MpServer', x=2856,53, y=8,62, z=-2479,58], EntityCow['Cow'/10876833, l='MpServer', x=2827,15, y=58,00, z=-2500,22], EntityItem['item.tile.sapling.acacia'/10876832, l='MpServer', x=2881,88, y=10,13, z=-2487,75], EntityCow['Cow'/10876834, l='MpServer', x=2881,44, y=63,00, z=-2441,78], EntityZombie['Zombie'/10876844, l='MpServer', x=2858,44, y=45,00, z=-2473,56], EntityZombie['Zombie'/10877036, l='MpServer', x=2857,91, y=45,00, z=-2475,56], EntitySkeleton['Skeleton'/10876843, l='MpServer', x=2857,50, y=45,00, z=-2473,50], EntityPig['Pig'/10876842, l='MpServer', x=2900,50, y=76,00, z=-2526,91], EntitySkeleton['Skeleton'/10877309, l='MpServer', x=2811,50, y=37,00, z=-2526,50], EntityZombie['Zombie'/10876991, l='MpServer', x=2864,13, y=46,00, z=-2479,28], EntitySkeleton['Skeleton'/10877188, l='MpServer', x=2869,50, y=10,00, z=-2434,50], EntityItem['item.tile.sapling.oak'/10876821, l='MpServer', x=2855,56, y=10,13, z=-2486,09], EntityItem['item.tile.log.oak'/10876820, l='MpServer', x=2856,13, y=7,13, z=-2483,13], EntityChicken['Chicken'/10876823, l='MpServer', x=2846,44, y=61,84, z=-2489,41], EntityItem['item.tile.sapling.birch'/10876822, l='MpServer', x=2843,84, y=7,13, z=-2484,69], EntitySheep['Sheep'/10876817, l='MpServer', x=2862,53, y=45,00, z=-2475,94], EntitySquid['Squid'/10877329, l='MpServer', x=2841,89, y=60,91, z=-2467,54], EntitySquid['Squid'/10877328, l='MpServer', x=2842,65, y=61,86, z=-2467,72], EntityItem['item.tile.log.birch'/10876819, l='MpServer', x=2850,16, y=7,13, z=-2483,88], EntityPig['Pig'/10876818, l='MpServer', x=2854,79, y=48,00, z=-2467,81], EntityItem['item.tile.sapling.acacia'/10876829, l='MpServer', x=2875,78, y=14,13, z=-2486,94], EntityItem['item.tile.sapling.acacia'/10876828, l='MpServer', x=2877,97, y=10,13, z=-2488,00], EntityChicken['Chicken'/10876831, l='MpServer', x=2828,47, y=60,00, z=-2489,56], EntitySheep['Sheep'/10876825, l='MpServer', x=2829,95, y=57,00, z=-2495,47], EntityChicken['Chicken'/10876824, l='MpServer', x=2832,56, y=58,62, z=-2493,53], EntityChicken['Chicken'/10876827, l='MpServer', x=2834,41, y=57,00, z=-2482,66], EntityPig['Pig'/10876826, l='MpServer', x=2835,81, y=56,00, z=-2483,81], EntitySkeleton['Skeleton'/10877146, l='MpServer', x=2836,50, y=5,00, z=-2527,50]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_20, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 295080576 bytes (281 MB) / 517996544 bytes (494 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	zyinhud{1.3.9} [Zyin's HUD] (ZyinsHUD-(1.7.10)-v.1.3.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 705/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (2)

**Comment by Zyin055** [comment]
Have you customized any of the key bindings? If so please post your ZyinHUD.cfg file located at /.minecraft/config/ZyinHUD.cfg. If not, try deleting your ZyinHUD.cfg file and see if the issue is resolved.

**Comment by Pystro** [comment]
Sorry, the problem resulved itself, so i cannot reproduce it any more.
