### ISSUE TITLE
Fatal CTD using FOV slider

### ISSUE THREAD

**Issue by OmegaCenti** [Zyin055/zyinhud#53]
- No mods installed except Forge and zyinhud installed

Replicated by a buddy in Germany as well. (He was too lazy to give me his crash report)

How to replicate: 
1. open minecraft (don't go into a world)
2. goto options
3. slide the FOV slider, should get a crash to desktop.

If only forge is installed (and no zyinhud) no issue with fov slider.
only shows up once zyinhud is enabled as a mod.

Following is a crash report 

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/16/16 1:05 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at com.zyin.zyinhud.gui.GuiZyinHUDOptions.ActionPerformedEventPost(GuiZyinHUDOptions.java:202)
    at com.zyin.zyinhud.ZyinHUDGuiEvents.ActionPerformedEventPost(ZyinHUDGuiEvents.java:27)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_ZyinHUDGuiEvents_ActionPerformedEventPost_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:468)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.zyin.zyinhud.gui.GuiZyinHUDOptions.ActionPerformedEventPost(GuiZyinHUDOptions.java:202)
    at com.zyin.zyinhud.ZyinHUDGuiEvents.ActionPerformedEventPost(ZyinHUDGuiEvents.java:27)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_ZyinHUDGuiEvents_ActionPerformedEventPost_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:468)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiOptions
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1114884368 bytes (1063 MB) / 1530920960 bytes (1460 MB) up to 9306112000 bytes (8875 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx9984m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.0.1684 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.0.1684-universal.jar) 
    UCHIJA  Forge{11.15.0.1684} [Minecraft Forge](forge-1.8.9-11.15.0.1684-universal.jar) 
    UCHIJA  zyinhud{1.4.8} [Zyin's HUD](ZyinsHUD-%281.8.8%29-v.1.4.8.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 980/PCIe/SSE2'
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
```

**Comment by OmegaCenti** [comment]
Also, I forgot to post the Forge log as well, which seems to have more information about which line in guiscreen.java is throwing the exception.

[13:05:47] [Client thread/INFO]: Setting user: OmegaCenti
[13:05:49] [Client thread/INFO]: LWJGL Version: 2.9.1
[13:05:51] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Zyin's HUD
[13:05:51] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:05:51] [Thread-9/INFO]: Initializing LWJGL OpenAL
[13:05:51] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:05:51] [Thread-9/INFO]: OpenAL initialized.
[13:05:52] [Sound Library Loader/INFO]: Sound engine started
[13:05:52] [Client thread/INFO]: Created: 16x16 textures-atlas
[13:05:52] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Zyin's HUD
[13:05:52] [Client thread/INFO]: SoundSystem shutting down...
[13:05:53] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[13:05:53] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:05:53] [Thread-15/INFO]: Initializing LWJGL OpenAL
[13:05:53] [Thread-15/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:05:53] [Thread-15/INFO]: OpenAL initialized.
[13:05:53] [Sound Library Loader/INFO]: Sound engine started
[13:05:54] [Client thread/INFO]: Created: 512x512 textures-atlas
[13:05:58] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1687) ~[ave.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024) ~[ave.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at com.zyin.zyinhud.gui.GuiZyinHUDOptions.ActionPerformedEventPost(GuiZyinHUDOptions.java:202) ~[GuiZyinHUDOptions.class:?]
    at com.zyin.zyinhud.ZyinHUDGuiEvents.ActionPerformedEventPost(ZyinHUDGuiEvents.java:27) ~[ZyinHUDGuiEvents.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_ZyinHUDGuiEvents_ActionPerformedEventPost_Post.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:468) ~[axu.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554) ~[axu.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523) ~[axu.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674) ~[ave.class:?]
    ... 17 more

**Comment by BBoldt** [comment]
Can confirm! @Zyin055 

https://github.com/BBoldt/ThePioneers/issues/9

**Comment by Zyin055** [comment]
I don't know how that could be throwing a null pointer exception and was unable to reproduce the crash you posted, but I did put a null pointer check that should prevent the crash from happening again. It'll be in the next build, 1.4.9.
